### ISSUE TITLE
Paper Problem

### ISSUE THREAD

**Issue by sheng-ri** [vectrix-space/ignite#42]
I'm running Ignite V0.4.0.
I use ignite boot paper for the use mixin.
but this has some problem with ignite work with paper.

# Paper 1.16 has the tab complete with colored tip.
-- But ignite can't adapt it.Even can't use tab. 
-- Maybe we need log4j2 plugin or other to Compatible with paper.
-- (In some case,console don't output anything, cursor on the last output up,Maybe is the windows cmd's problem)

# Debug.log output a lot about Minecraft Packet to the Client.
-- such as ([Netty Server IO #1/DEBUG] [net.minecraft.server.v1_16_R3.PacketEncoder]: OUT: [PLAY:70] net.minecraft.server.v1_16_R3.PacketPlayOutEntityVelocity)
-- It can make log file very big.

# Log format problem
-- [186月2021 17:08:23] [main/DEBUG] [mixin]: Initialising Mixin Platform Manager
-- In Chinese,We generally format time like "yyyy MM dd",but output print like "dd mm月 yyyy"
-- This is not a serious problem.

Sorry for the grammar problem,I'm not good at english.
The most serious problem is packet debug output,It seems make the network lag,But tps is 20.
Mixin is very compatible with paper(currently)
Thanks for ignite.

**Comment by connorhartley** [comment]
I will check if a lot of these logging / console issues occur on the latest 0.5.0 snapshot and get back to you on this.

**Comment by sheng-ri** [comment]
> I will check if a lot of these logging / console issues occur on the latest 0.5.0 snapshot and get back to you on this.

Thanks a lot! :>

**Comment by connorhartley** [comment]
> Paper 1.16 has the tab complete with colored tip.
-- But ignite can't adapt it.Even can't use tab.
-- Maybe we need log4j2 plugin or other to Compatible with paper.
-- (In some case,console don't output anything, cursor on the last output up,Maybe is the windows cmd's problem)

I've just checked this on the new version and this appears to be working. 

![tabcomplete](https://user-images.githubusercontent.com/12867785/122620696-b6ede980-d0e7-11eb-8171-e266c8bca1c1.PNG)

> Debug.log output a lot about Minecraft Packet to the Client.
-- such as ([Netty Server IO #1/DEBUG] [net.minecraft.server.v1_16_R3.PacketEncoder]: OUT: [PLAY:70] net.minecraft.server.v1_16_R3.PacketPlayOutEntityVelocity)
-- It can make log file very big.

This should be fixed in the new version too, because of the filters (https://github.com/vectrix-space/ignite/blob/dev/launcher/src/main/resources/log4j2.xml#L46-L50).

> Log format problem
-- [186月2021 17:08:23] [main/DEBUG] [mixin]: Initialising Mixin Platform Manager
-- In Chinese,We generally format time like "yyyy MM dd",but output print like "dd mm月 yyyy"
-- This is not a serious problem.

I don't think I'll be changing this, I'm hoping that most people will be able to recognize the format (or recognize the difference in this case). Perhaps you could compile Ignite yourself and swap them around in the log4j configuration if it's a big problem.

The update for 0.5.0 is a work in progress, so it'll be a little bit before there is a build available. I will try get some snapshot builds going soon. The update will also contain some breaking changes that will affect your mods, so make sure you account for that.

**Comment by sheng-ri** [comment]
I see,I'll wait for the 0.5.0.

**Comment by connorhartley** [comment]
You can find the newest version here: https://github.com/vectrix-space/ignite/releases/tag/v0.5.0
